### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by risseraka**

### CODE REVIEW

**Comment by vvo** [comment]
But google disagree?

https://www.google.fr/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#safe=off&q=%22in+it%27s+full+length%22
https://www.google.fr/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#safe=off&q=%22in+its+full+length%22

**Comment by risseraka** [comment]
"Either in it is full length"
or
"Either in his full length"
Definitely its => possessive.

**Comment by vvo** [comment]
Lol I failed at my own code, I thought you changed its for it's

**Comment by vvo** [comment]
sorry

**Comment by risseraka** [comment]
I'll get super famous now! :ok_hand:

**Pull request merged**
