### PR TITLE
Add option for no-loop. Fixes #66

### LINKED ISSUE #66: Suggestion: no-loop option

### PR DESCRIPTION
**Pull request by karanjthakkar**

### CODE REVIEW

**Comment by karanjthakkar** [comment]
@vvo Let me know what you think of this :)

**Comment by vvo** [comment]
Well that's awesome, can you add the relevant documentation @karanjthakkar?

**Comment by karanjthakkar** [comment]
@vvo I've added an entry in the README as well. Would that be enough or do you want me to add it somewhere else as well?

**Comment by vvo** [comment]
That's enough I think

**Comment by vvo** [comment]
thanks a lot!

**Comment by karanjthakkar** [comment]
@vvo Glad to help 💯

**Pull request merged**
